tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://getcloudify.org/spec/cloudify/5.0.5/types.yaml
  - plugin:cloudify-kubernetes-plugin?version= >=2.7.0

inputs:

  kubernetes_master_endpoint:
    type: string

  kubernetes_client_config:
    default:
      configuration:
        api_options:
          host: { get_input: kubernetes_master_endpoint }
          api_key: { get_secret: kubernetes_token }
          debug: false
          verify_ssl: false


  validate_status:
    default: false

  database_user:
    type: string
    default: drupal

  database_password:
    type: string
    default: 'U2FsdGVkX19VxMEA6AdZt5fccsn/JsFU4eGpttt13JI='

  database_name:
    type: string
    default: drupal

  load_balancer_deployment:
    type: string
    description: The deployment ID of the DB LB APP lb deployment. Usually either 'lb', 'public-cloud-lb', or 'private-cloud-lb'.
    default: aws-lb

  kubernetes_deployment:
    type: string
    description: The deployment ID of the Kubernetes deployment.
    default: kubernetes

node_templates:

  wordpress:
    type: cloudify.kubernetes.resources.FileDefinedResource
    properties:
      client_config: { get_input: kubernetes_client_config }
      validate_resource_status: { get_input: validate_status }
      file:
        resource_path: resources/resources.yaml
        template_variables:
          WORDPRESS_DB_USER: { get_input: database_user }
          WORDPRESS_DB_PASSWORD: { get_input: database_password  }
          WORDPRESS_DB_HOST: { get_capability: [ { get_input: load_balancer_deployment }, endpoint ] }
          WORDPRESS_DB_NAME: { get_input: database_name }

outputs:
  app_login:
    value:
      concat:
      - 'http://'
      - { get_capability: [ { get_input: kubernetes_deployment }, node-endpoint ] }
      - ':'
      - '30080'
